pipeline {
    agent any
    environment {
        ENVIRONMENT   = "dev"
        REGION        = "us-east-1"
        INSTANCE_TYPE = "t2.micro"
    }
    stages{
        stage('init') {
            steps{
                sh 'terraform init -no-color'
            }
            
        }
        stage('validate') {
            steps{
                sh 'terraform validate -no-color'
            }
            
        }
         stage('plan') {
            steps {
                sh '''
                    terraform plan -no-color \
                    -var="ENVIRONMENT=${ENVIRONMENT}" \
                    -var="REGION=${REGION}" \
                    -var="INSTANCE_TYPE=${INSTANCE_TYPE}"
                '''
            }
        }
        stage('format') {
            steps{
                sh 'terraform fmt -no-color'
            }
            
        }
        stage('Plan') {
            steps{
                sh 'terraform plan -no-color -var-file="terraform.tfvars"'
                
            }
            
        }
    }
}